# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9f3e9e51f459026d416ef3e09e7475f881c62ace6b11529f59cb11e5970c914c97567b16d9049cfcccbfc02f5592fdee27d3dd68ac3e12cf3f93af55e54eab

test:
  secret_key_base: efa32025f1a7e1e0fda6d116000668bf4864c83a29edb47dcfaa4553783fc069c7ce638fbfcdbcbd2c0012f1eee184cc43125115be6ab5c202f01c167e5d9389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
